### ISSUE TITLE
cannot start after changing colours

### ISSUE THREAD

**Issue by NicolasWi** [vlachoudis/bCNC#1008]
Hello,

After changing the background color to black and back to white,
the program doesnt launch. (windows 7 32 bit)
i have reinstalled python 2.7.15
i have downloaded the zip file again
`Traceback (most recent call last):
  File "C:\Users\homeuser\Desktop\bCNC-master\ToolsPage.py", line 931, in __init__
    exec("import %s"%(name))
  File "<string>", line 1, in <module>
  File "C:\Users\homeuser\Desktop\bCNC-master\plugins\slicemesh.py", line 26, in <module>
    import numpy as np
ImportError: No module named numpy

Traceback (most recent call last):
  File "C:\Users\homeuser\Desktop\bCNC-master\bCNC.py", line 2592, in <module>
    application = Application(tk)
  File "C:\Users\homeuser\Desktop\bCNC-master\bCNC.py", line 175, in __init__
    self.canvasFrame = CNCCanvas.CanvasFrame(frame, self)
  File "C:\Users\homeuser\Desktop\bCNC-master\CNCCanvas.py", line 1960, in __init__
    self.canvas = CNCCanvas(self, app, takefocus=True, background="White")
  File "C:\Users\homeuser\Desktop\bCNC-master\CNCCanvas.py", line 277, in __init__
    self.initPosition()
  File "C:\Users\homeuser\Desktop\bCNC-master\CNCCanvas.py", line 1329, in initPosition
    self.configure(background=CANVAS_COLOR)
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1330, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 1321, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
TclError: unknown color name ""`

**Comment by Harvie** [comment]
please update to latest git and install numpy module to your python.
