### ISSUE TITLE
unable to send gcode from ubuntu 18.04

### ISSUE THREAD

**Issue by Cdriko** [vlachoudis/bCNC#1067]
hello
I try to use bCNC with grbl and ubuntu 18.04 fresh install.

I installer python-serial via apt and pip2 install pserial.
alas, after the soft has been connected to the machine (and the icon connected ok), no gcode sended has no effect, and I get in the terminal :
`Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cedric/.local/lib/python2.7/site-packages/bCNC/Sender.py", line 875, in serialIO
    self.mcontrol.parseBracketAngle(line, cline)
  File "/home/cedric/.local/lib/python2.7/site-packages/bCNC/controllers/GRBL0.py", line 84, in parseBracketAngle
    self.master.log.put((Sender.MSG_RECEIVE, line))
NameError: global name 'Sender' is not defined
`

note that I've same result with the both grbl protocols

**Comment by Cdriko** [comment]
grbl 1.1

**Comment by tuxBurner** [comment]
I have the same problem under ubuntu 18.10 

```
 python2 -m bCNC

new-config Utils <ConfigParser.ConfigParser instance at 0x7f4624be3bd8>
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tuxburner/.local/lib/python2.7/site-packages/bCNC/Sender.py", line 875, in serialIO
    self.mcontrol.parseBracketAngle(line, cline)
  File "/home/tuxburner/.local/lib/python2.7/site-packages/bCNC/controllers/GRBL0.py", line 84, in parseBracketAngle
    self.master.log.put((Sender.MSG_RECEIVE, line))
NameError: global name 'Sender' is not defined

```

**Comment by Harvie** [comment]
I think you don't have latest version of bCNC. This was already fixed in 0.9.14.42

```
# pip2 show bCNC
Name: bCNC
Version: 0.9.14.42
```

**Comment by Harvie** [comment]
I've took second look and this is a different problem. I'll have to fix it.

**Comment by Harvie** [comment]
I maybe fixed it. Try git or 0.9.14.43

**Comment by tuxBurner** [comment]
Thanks a lot it is working now :)
