### ISSUE TITLE
Error found?

### ISSUE THREAD

**Issue by flaplante** [vlachoudis/bCNC#1174]
F.Y.I. 
Using current release installed last night on Windows 10 using 'pip -install bcnc'.
When I click 'check for update' in the ABOUT dialog, I get the following:

c:\Python27>python -m bCNC
new-config Utils <ConfigParser.ConfigParser instance at 0x00000000035C3788>
Traceback (most recent call last):
  File "c:\Python27\lib\site-packages\bCNC\Utils.py", line 460, in __call__
    return self.func(*args)
  File "c:\Python27\lib\site-packages\bCNC\Updates.py", line 149, in check
    if self.isNewer(latest_version):
  File "c:\Python27\lib\site-packages\bCNC\Updates.py", line 131, in isNewer
    av = map(int, self.version.split("."))
ValueError: invalid literal for int() with base 10: '14-dev'

**Comment by Harvie** [comment]
Yes. "check for update" code is obsolete right now. it needs to be replaced.
You can check for upgrades as follows `pip install --upgrade bCNC`
