### ISSUE TITLE
Negative probe distance causes exception

### ISSUE THREAD

**Issue by crioux** [vlachoudis/bCNC#1288]
If you specify a negative probing distance (it's unclear if probing distance is being added or subtracted from Z during the probe operation...), things crash on exit. Also the 'send email about the crash' box is broken as well.

Python 2.7.16, Win64, running on Windows 10

1. Launch bCNC 0.9.14-dev
2. Go to Probe menu
3. Click 'Tool'
4. Put '-66' in as the distance
5. Exit
```
new-config Utils <ConfigParser.ConfigParser instance at 0x00000000031C02C8>
self.canvas.winfo_id(): 2425352
Using old style comports()!
Using old style comports()!
Using old style comports()!
Controller state changed to: Alarm (Running: False)
probe chg handler
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bCNC\Utils.py", line 464, in __call__
    return self.func(*args)
  File "C:\Python27\lib\site-packages\bCNC\ProbePage.py", line 1889, in setProbeParams
    CNC.vars["tooldistance"] = float(self.probeDistance.get())
ValueError: could not convert string to float: -
probe chg handler
probe chg handler
probe chg handler
probe chg handler
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bCNC\Utils.py", line 464, in __call__
    return self.func(*args)
  File "C:\Python27\lib\site-packages\bCNC\ProbePage.py", line 1889, in setProbeParams
    CNC.vars["tooldistance"] = float(self.probeDistance.get())
ValueError: could not convert string to float: -
probe chg handler
probe chg handler
probe chg handler
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\bCNC\Utils.py", line 464, in __call__
    return self.func(*args)
  File "C:\Python27\lib\site-packages\bCNC\__main__.py", line 544, in quit
    Utils.ReportDialog.sendErrorReport()
  File "C:\Python27\lib\site-packages\bCNC\Utils.py", line 628, in sendErrorReport
    ReportDialog(None)
  File "C:\Python27\lib\site-packages\bCNC\Utils.py", line 538, in __init__
    from bCNC import __version__, __date__
ImportError: cannot import name __version__
```

**Comment by Harvie** [comment]
It says `ValueError: could not convert string to float: -`

This means you didn't really entered negative number like "-23", you just entered "-".
But i understand this is likely to happen when entering the number, because the number gets evaluated even before you type the whole thing. This is rather cosmetic problem... But hey, we might fix it some day...
