### ISSUE TITLE
Won't load on older Mac (TypeError: cannot concatenate 'str' and 'NoneType' objects)

### ISSUE THREAD

**Issue by natevw** [vlachoudis/bCNC#1294]
I am trying bCNC on an older MacBook running OS X 10.9.5, Python 2.7.9. Installation went okay once I updated pip/setuptools, but when trying to launch I get an error:

```
new-config Utils <ConfigParser.ConfigParser instance at 0x109aadf80>
self.canvas.winfo_id(): -2067257328
Using old style comports()!
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/bCNC/__main__.py", line 2708, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/bCNC/__main__.py", line 2676, in main
    application = Application(tk)
  File "/usr/local/lib/python2.7/site-packages/bCNC/__main__.py", line 196, in __init__
    page = cls(self.ribbon, self)
  File "/usr/local/lib/python2.7/site-packages/bCNC/CNCRibbon.py", line 115, in __init__
    self.register()
  File "/usr/local/lib/python2.7/site-packages/bCNC/FilePage.py", line 395, in register
    (SerialFrame,))
  File "/usr/local/lib/python2.7/site-packages/bCNC/CNCRibbon.py", line 134, in _register
    w = f(self.master._pageFrame, self.app)
  File "/usr/local/lib/python2.7/site-packages/bCNC/FilePage.py", line 253, in __init__
    self.comportRefresh()
  File "/usr/local/lib/python2.7/site-packages/bCNC/FilePage.py", line 351, in comportRefresh
    hwgrep += ["hwgrep://"+hw+"\t"+i[1]]
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

I tracked this down to having some `None` values apparently not expected in the `comports()` return:

```
[['/dev/cu.Bluetooth-Incoming-Port', 'n/a', 'n/a'], ['/dev/cu.Bluetooth-Modem', 'n/a', 'n/a'], ['/dev/cu.usbmodem411', None, 'USB VID:PID=2341:43 SNR=553303336303516131E0']]
```

So to workaround, I added the following in FilePage.py:

```
def comportsGet(self):
		try:
			return comports(include_links=True)
		except TypeError:
			print("Using old style comports()!")
			tmp = comports()
			for i in tmp:
				if i[1] is None: i[1] = '-'
			return tmp
```

**Comment by Harvie** [comment]
This looks somewhat fixable. However is there reason why not to upgrade python to latest  2.7.x version?

**Comment by Harvie** [comment]
Hello guys, some offtopic mesage: There is new bCNC version coming and it's really challenging to get it working on Mac OS, because i don't have mac.
Currently the new version resides in https://github.com/koneklaudio/bCNC but i will merge it soon. Can you please help me debug it on MacOS? We are discussing the issues here: https://github.com/vlachoudis/bCNC/issues/591
