### ISSUE TITLE
upgrade then it does'nt run anymore

### ISSUE THREAD

**Issue by dhuvelle** [vlachoudis/bCNC#1314]
Hello everyone, 

I'm have troubles since i upgraded with "python -m pip install --upgrade bCNC". I'm no more able to launch bCNC and it says me the following lines

`C:\Users\dhuve>python -m pip install --upgrade https://github.com/vlachoudis/bCNC/archive/master.zip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting https://github.com/vlachoudis/bCNC/archive/master.zip
  Downloading https://github.com/vlachoudis/bCNC/archive/master.zip
     | 7.2MB 4.9MB/s
Requirement already satisfied, skipping upgrade: numpy>=1.12 in c:\python27\lib\site-packages (from bCNC==0.9.14.301) (1.16.5)
Requirement already satisfied, skipping upgrade: Pillow>=4.0 in c:\python27\lib\site-packages (from bCNC==0.9.14.301) (6.2.1)
Requirement already satisfied, skipping upgrade: pyserial<=3.0.1 in c:\python27\lib\site-packages (from bCNC==0.9.14.301) (3.0.1)
Requirement already satisfied, skipping upgrade: opencv-python>=2.4 in c:\python27\lib\site-packages (from bCNC==0.9.14.301) (4.1.2.30)
Installing collected packages: bCNC
  Found existing installation: bCNC 0.9.14.301
    Uninstalling bCNC-0.9.14.301:
      Successfully uninstalled bCNC-0.9.14.301
    Running setup.py install for bCNC ... done
Successfully installed bCNC-0.9.14.301

C:\Users\dhuve>python -m bCNC
new-config Utils <ConfigParser.ConfigParser instance at 0x0000000002DED408>
================================================================================
WARNING: bCNC has been recently ported to support both python v2.x and v3.x
Most things seem to work reasonably well in both python versions.
Please report any issues to: https://github.com/vlachoudis/bCNC/issues
================================================================================
self.canvas.winfo_id(): 17435774
Using old style comports()!
Using old style comports()!
Using old style comports()!
C:\Python27\lib\site-packages\bCNC\ProbePage.py:1876: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  CNC.toolWaitAfterProbe = int(TOOL_WAIT.index(self.toolWait.get()))
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\lib\site-packages\bCNC\__main__.py", line 2715, in <module>
    main()
  File "C:\Python27\lib\site-packages\bCNC\__main__.py", line 2683, in main
    application = Application(tk)
  File "C:\Python27\lib\site-packages\bCNC\__main__.py", line 196, in __init__
    page = cls(self.ribbon, self)
  File "C:\Python27\lib\site-packages\bCNC\CNCRibbon.py", line 115, in __init__
    self.register()
  File "C:\Python27\lib\site-packages\bCNC\ProbePage.py", line 1987, in register
    (ProbeCommonFrame, ProbeFrame, AutolevelFrame, CameraFrame, ToolFrame))
  File "C:\Python27\lib\site-packages\bCNC\CNCRibbon.py", line 134, in _register
    w = f(self.master._pageFrame, self.app)
  File "C:\Python27\lib\site-packages\bCNC\ProbePage.py", line 1667, in __init__
    self.toolWait.set(TOOL_WAIT[1])
  File "C:\Python27\lib\site-packages\bCNC\lib\tkExtra.py", line 3094, in set
    self.invoke()
  File "C:\Python27\lib\site-packages\bCNC\lib\tkExtra.py", line 3046, in invoke
    self.command()
  File "C:\Python27\lib\site-packages\bCNC\ProbePage.py", line 1876, in waitChange
    CNC.toolWaitAfterProbe = int(TOOL_WAIT.index(self.toolWait.get()))
ValueError: u'AVANT & APR\xc8S sondage' is not in list`

thank you for your help, i'm just following steps, I don't know what i'm doing ...

**Comment by Harvie** [comment]
We need to take a look at this. If you need bCNC in the meantime, you can downgrade as workaround. Eg. using:

`pip install bCNC==0.9.14.300`
or even
`pip install bCNC==0.9.14.62`
