### ISSUE TITLE
bCNC freezes on pocket action

### ISSUE THREAD

**Issue by AlfredoCubitos** [vlachoudis/bCNC#1349]
Hi,

after clicking the Pocket button twice bCNC freezes with this error:

```
self.canvas.winfo_id(): 100663381
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/bCNC/Utils.py", line 464, in __call__
    return self.func(*args)
  File "/usr/lib/python3.7/site-packages/bCNC/ToolsPage.py", line 1747, in execute
    self.tools.getActive().execute(self.app)
  File "/usr/lib/python3.7/site-packages/bCNC/ToolsPage.py", line 909, in execute
    app.pocket(name)
  File "/usr/lib/python3.7/site-packages/bCNC/__main__.py", line 1827, in pocket
    msg = self.gcode.pocket(blocks, diameter, stepover, name)
  File "/usr/lib/python3.7/site-packages/bCNC/CNC.py", line 4011, in pocket
    newpath.extend(self._pocket(path, -D*diameter, stepover, 0))
TypeError: 'NoneType' object is not iterable
```
steps to reproduce:
1. select object
2. click Pocket -> everything ok, showing the path
3. click Pocket again -> freeze :-(

I found out, that this seems to be happen when no object is selected

**Comment by MARIOBASZ** [comment]
if the bit diameter does not have space inside the silhouette to generate pocket, that serious error occurs

**Comment by gnurc** [comment]
Ok, Thank you.

**Comment by Harvie** [comment]
There is new pocketing tool called "offset" in latest bCNC which is not affected by this crash, old profile/pocket tools will be removed in future release.
Please test it and we will reopen the issue if the problem persits.
