### ISSUE TITLE
bCNC states not connected but homing etc works

### ISSUE THREAD

**Issue by FischOderAal** [vlachoudis/bCNC#1391]
For whichever reason the status in bCNC is not updated to IDLE. I can correctly connect to grbl and homing as well as moving the axis works. When I hit a physical end switch it also goes to the corresponding error. I cannot clear the error, it persists through resets. When I enter "?" in the terminal it gives the correct response (IDLE and the position).

What I did:
* updated PIP to the latest version
* tried setting $10=1, but no improvement 

No improvement. I'm on windows 10 and have Python 2.7.18 installed. The GRBL version is 0.9.59. In the command Window it says:
> self.canvas.winfo_id(): 1116012
> Using old style comports()!
> Using old style comports()!
> Using old style comports()!
> Not Loading 6 axis displays
> Not Loading 6 axis displays

Now some more items occured:

> Traceback (most recent call last):
>   File "C:\Program Files\Python 2\lib\site-packages\bCNC\__main__.py", line 2516, in monitorSerial
>     self._monitorSerial()
>   File "C:\Program Files\Python 2\lib\site-packages\bCNC\__main__.py", line 2394, in _monitorSerial
>     self.terminal.itemconfig(pos, foreground="Blue")
>   File "C:\Program Files\Python 2\lib\lib-tk\Tkinter.py", line 2692, in itemconfigure
>     return self._configure(('itemconfigure', index), cnf, kw)
>   File "C:\Program Files\Python 2\lib\lib-tk\Tkinter.py", line 1327, in _configure
>     self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
> TclError: item number "-2" out of range

**Comment by FischOderAal** [comment]
Noone?
