### ISSUE TITLE
Compiled EXE Works in BCNC Directory, but not externally

### ISSUE THREAD

**Issue by sambartle** [vlachoudis/bCNC#1424]
EXE's built from the latest git source dont seem to execute when outisde of the python environment. 

I installed the latest bCNC using pip from git, and it works perfectly. 

I then decided to use the make_exe.bat to create the exe which fails to load with the following error

```
Traceback (most recent call last):
  File "PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 13, in <module>
  File "c:\users\test\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "pkg_resources\__init__.py", line 85, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[3652] Failed to execute script pyi_rth_pkgres
```

Unfortunately I'm fairly new to python so Im not sure how to resolve either issue. Hoping someone can point me in the right direction.

Thanks

**Comment by sambartle** [comment]
Closed as I did a terrible job describing issue.
