### ISSUE TITLE
Error on exiting bCNC

### ISSUE THREAD

**Issue by water-rhatt** [vlachoudis/bCNC#1463]
I get this error when I exit. Is this a known issue with a fix? Seems like somewhere it is adding three decimal places to an integer, but that's all I know. It doesn't seem to keep bCNC from running the next time.

```
Program     : bCNC
Version     : 0.9.14-dev
Last Change : 8 Jan 2019
Platform    : linux2
Python      : 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 9.2.1 20191008]
TkVersion   : 8.6
TclVersion  : 8.6

Traceback:
Traceback (most recent call last):
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/Utils.py", line 464, in __call__
    return self.func(*args)
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/bCNC.py", line 2011, in loadDialog
    if filename: self.load(filename)
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/bCNC.py", line 2089, in load
    Page.frames["CAM"].populate()
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/ToolsPage.py", line 1709, in change
    tool.populate()
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/ToolsPage.py", line 1065, in populate
    self.values[n] = int(CNC.vars[n])
ValueError: invalid literal for int() with base 10: '250.000'

Traceback (most recent call last):
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/Utils.py", line 464, in __call__
    return self.func(*args)
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/bCNC.py", line 2011, in loadDialog
    if filename: self.load(filename)
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/bCNC.py", line 2089, in load
    Page.frames["CAM"].populate()
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/ToolsPage.py", line 1709, in change
    tool.populate()
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/ToolsPage.py", line 1065, in populate
    self.values[n] = int(CNC.vars[n])
ValueError: invalid literal for int() with base 10: '250.000'

Traceback (most recent call last):
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/Utils.py", line 464, in __call__
    return self.func(*args)
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/bCNC.py", line 2011, in loadDialog
    if filename: self.load(filename)
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/bCNC.py", line 2089, in load
    Page.frames["CAM"].populate()
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/ToolsPage.py", line 1709, in change
    tool.populate()
  File "/home/randolph/.local/lib/python2.7/site-packages/bCNC/ToolsPage.py", line 1065, in populate
    self.values[n] = int(CNC.vars[n])
ValueError: invalid literal for int() with base 10: '250.000'
```

**Comment by Harvie** [comment]
Should probably be replaced with `float('250.000')` or `int(float('250.000'))`. not sure...
