### ISSUE TITLE
Web Pendant, Picture flickering

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#1509]
Happy New year.
I have a Problem with the Web Pendant.
It is the same on Windows, Linux, Android and every Browser i can use.
bCNC is installed on Lubuntu.

https://user-images.githubusercontent.com/14917841/104018878-dbe64400-51ba-11eb-83a2-b44c898ca375.mp4

**Comment by GitHubCaps** [comment]
@Guenni75 Have you tried directly from bCNC first?

Make sure that you are connected to pendant and can run some code locally via bCNC through the pendant.

Personally, I stopped using Lubuntu a long time ago because of issues with camera, web, etc. I found Linux Mint XFCE versions to fit the bill a bit better, I use the 32-bit versions for my old machines and of course the 64-bit for the newer. I stay away from Cinnamon and Mate, because I prefer lightweight OSes myself.

**Comment by GitHubCaps** [comment]
@Guenni75 Did some further investigating on my end and it does have an issue when opening a file in pendant. It works in Python2, however it needs patching for Python3.

I will reply back as soon as I have a patch for it.

**Comment by GitHubCaps** [comment]
@Guenni75 and anyone else that would like to test the following before a commit.

Tested in python 2.7.14 (already worked there) and 3.8.2 (lots of issues there)
[Pendant.py.zip](https://github.com/vlachoudis/bCNC/files/5792214/Pendant.py.zip)

`Pendant.py` for those that don't like to download anything suspicious:
```python
# -*- coding: ascii -*-
# $Id$
#
# Author: Vasilis Vlachoudis
# Email:  vvlachoudis@gmail.com
# Date:   24-Aug-2014

from __future__ import absolute_import
from __future__ import print_function
__author__ = "Vasilis Vlachoudis"
__email__  = "Vasilis.Vlachoudis@cern.ch"

import os
import re
import sys
#import cgi
import json
#import urllib
import tempfile
import threading

# ---------------------------------------
# For debugging issues
# ---------------------------------------
import traceback
from errno import EPIPE
try:
	broken_pipe_error = BrokenPipeError  # Python3 has: BrokenPipeError
except NameError:
	broken_pipe_error = IOError
# ---------------------------------------

try:
	import urllib.parse as urlparse
	from urllib.parse import unquote
except ImportError:
	import urlparse
	from urllib import unquote as unquote

try:
	import http.server as HTTPServer
except ImportError:
	import BaseHTTPServer as HTTPServer

try:
	from PIL import Image
except ImportError:
	Image = None

from CNC import CNC
from Utils import prgpath
import Camera

HOSTNAME = "localhost"
port     = 8080

httpd    = None
webpath  = "%s/pendant"%(prgpath)
iconpath = "%s/icons/"%(prgpath)


#==============================================================================
# Simple Pendant controller for CNC
#==============================================================================
class Pendant(HTTPServer.BaseHTTPRequestHandler):
	camera = None

	#----------------------------------------------------------------------
	def log_message(self, fmt, *args):
		# Only log requests to the main page, ignore the rest
		if args[0].startswith("GET / ") or args[0].startswith("GET /send"):
			args = list(args)
			args[0] = "%s : %s"%(self.address_string(),args[0])
			HTTPServer.BaseHTTPRequestHandler.log_message(self, fmt, *args)

	#----------------------------------------------------------------------
	def do_HEAD(self, rc=200, content="text/html", cl=0):
		self.send_response(rc)
		self.send_header("Content-type", content)
		if cl != 0:
			self.send_header("Content-length", cl)
		self.end_headers()

	#----------------------------------------------------------------------
	def do_GET(self):
		"""Respond to a GET request."""
		if "?" in self.path:
			page,arg = self.path.split("?",1)
			arg = dict(urlparse.parse_qsl(arg))
		else:
			page = self.path
			arg = None

#		print(self.path,type(self.path))
#		print(page)
#		print(arg)

		if   page == "/send":
			if arg is None: return
			for (key,value) in arg.items():
				if key=="gcode":
					for line in value.split('\n'):
						httpd.app.queue.put('%s\n'%(line))
				elif key=="cmd":
					httpd.app.pendant.put(unquote(value))
			# Send empty response so browser does not generate errors
			self.do_HEAD(200, "text/text", cl=len(""))
			self.wfile.write("".encode())

		elif page == "/state":
			tmp = {}
			for name in ["controller", "state", "pins", "color", "msg", "wx", "wy", "wz", "G", "OvFeed", "OvRapid", "OvSpindle"]:
				tmp[name] = CNC.vars[name]
			contentToSend = json.dumps(tmp)
			self.do_HEAD(200, content="text/text", cl=len(contentToSend))
			self.wfile.write(contentToSend.encode())

		elif page == "/config":
			snd = {}
			snd["rpmmax"] = httpd.app.get("CNC","spindlemax")
			contentToSend = json.dumps(snd)
			self.do_HEAD(200, content="text/text", cl=len(contentToSend))
			self.wfile.write(contentToSend.encode())

		elif page == "/icon":
			if arg is None: return
			filename = os.path.join(iconpath, arg["name"]+".gif")
			self.do_HEAD(200, content="image/gif", cl=os.path.getsize(filename))
			try:
				f = open(filename,"rb")
				self.wfile.write(f.read())
				f.close()
			except:
				pass

		elif page == "/canvas":
			if not Image: return
			with tempfile.NamedTemporaryFile(suffix='.ps') as tmp:
				httpd.app.canvas.postscript(
					file=tmp.name,
					colormode='color',
				)
				tmp.flush()
				try:
					with tempfile.NamedTemporaryFile(suffix='.gif') as out:
						Image.open(tmp.name).save(out.name, 'GIF')
						out.flush()
						out.seek(0)
						self.do_HEAD(200, content="image/gif", cl=os.path.getsize(tmp.name))

#						self.wfile.write(out.read())
						try:
							self.wfile.write(out.read())
						except broken_pipe_error as exc: # [Errno 32] Broken pipe
							if broken_pipe_error == IOError:
								if exc.errno != EPIPE:
									raise
#							print('do_GET:\n  %s: %s [Errno %s] [EPIPE %s]'%(
#									broken_pipe_error, exc, exc.errno, EPIPE))
#							print(traceback.format_exc())

				except:
					filename = os.path.join(iconpath, "warn.gif")
					self.do_HEAD(200, content="image/gif", cl=os.path.getsize(filename))
					try:
						f = open(filename,"rb")
						self.wfile.write(f.read())
						f.close()
					except:
						pass

		elif page == "/camera":
			if not Camera.hasOpenCV(): return
			if Pendant.camera is None:
				Pendant.camera = Camera.Camera("webcam")
				Pendant.camera.start()

			if Pendant.camera.read():
				Pendant.camera.save("camera.jpg")
				#cv.imwrite("camera.jpg",img)
				self.do_HEAD(200, content="image/jpeg", cl=os.path.getsize("camera.jpg"))
				try:
					f = open("camera.jpg","rb")
					self.wfile.write(f.read())
					f.close()
				except:
					pass
		else:
			self.mainPage(page[1:])

	#----------------------------------------------------------------------
	def deal_post_data(self):
		boundary = None  # FIX: UnboundLocalError: local variable 'boundary' referenced before assignment

		#boundary = self.headers.plisttext.split("=")[1]  # AttributeError: 'HTTPMessage' object has no attribute 'plisttext'
		try:
			boundary = self.headers.plisttext.split("=")[1]  # plisttext is from mimetools and has been deprecated in favor of email, but whatever!
		except Exception as exc:
			#print('deal_post_data:\n  Exception: %s'%(exc))
			boundary = self.headers.get_boundary()           # HTTPMessage has this, though

		if boundary is None:
			return (False, "boundary is None")

		remainbytes = int(self.headers['content-length'])
		#line = self.rfile.readline()
		line = self.rfile.readline().decode()
		remainbytes -= len(line)

		if not boundary in line:
			return (False, "Content NOT begin with boundary")

		#line = self.rfile.readline()
		line = self.rfile.readline().decode()
		remainbytes -= len(line)
		fn = re.findall(r'Content-Disposition.*name="file"; filename="(.*)"', line)
		if not fn:
			return (False, "Can't find out file name...")
		path = os.path.expanduser("~")
		path = os.path.join(path, "bCNCUploads")
		if not os.path.exists(path):
		    os.makedirs(path)
		fn = os.path.join(path, fn[0])
		#line = self.rfile.readline()
		line = self.rfile.readline().decode()
		remainbytes -= len(line)
		#line = self.rfile.readline()
		line = self.rfile.readline().decode()
		remainbytes -= len(line)
		try:
			out = open(fn, 'wb')
#		except IOError:
		except Exception as exc:
			print('deal_post_data:\n  Exception: %s'%(exc))
			return (False, "Can't create file to write, do you have permission to write?")

		#preline = self.rfile.readline()
		preline = self.rfile.readline().decode()
		remainbytes -= len(preline)
		while remainbytes > 0:
			#line = self.rfile.readline()
			line = self.rfile.readline().decode()
			remainbytes -= len(line)
			if boundary in line:
				preline = preline[0:-1]
				if preline.endswith('\r'):
					preline = preline[0:-1]
				#out.write(preline)
				if isinstance(preline, bytes):
					out.write(preline)
				else:
					out.write(preline.encode())

				out.close()
				return (True, "%s" % fn)
			else:
				#out.write(preline)
				if isinstance(preline, bytes):
					out.write(preline)
				else:
					out.write(preline.encode())

				preline = line
		return (False, "Unexpected End of data.")

	#----------------------------------------------------------------------
	def do_POST(self):
		result,fMsg = self.deal_post_data()
		if(result):
			httpd.app._pendantFileUploaded = fMsg
		# Send empty response so browser does not generate errors
		#self.do_HEAD(200, "text/text")
		try:
			self.do_HEAD(200, "text/text")
		except Exception as exc:
			print('do_POST:\n  Exception: %s'%(exc))

	# ---------------------------------------------------------------------
	def mainPage(self, page):
		global webpath

		# Handle certain filetypes
		filetype = page.rpartition('.')[2]
		if   filetype == "css": self.do_HEAD(content="text/css")
		elif filetype == "js":  self.do_HEAD(content="application/x-javascript")
		elif filetype == "json": self.do_HEAD(content="application/json")
		elif filetype == "jpg" or filetype == "jpeg" : self.do_HEAD(content="image/jpeg")
		elif filetype == "gif": self.do_HEAD(content="image/gif")
		elif filetype == "png": self.do_HEAD(content="image/png")
		elif filetype == "ico": self.do_HEAD(content="image/x-icon")
		else: self.do_HEAD()

		if page == "": page = "index.html"
		try:
			f = open(os.path.join(webpath,page),"rb")
			self.wfile.write(f.read())
			f.close()
#		except IOError:  # XXX: This was blocking: FileNotFoundError
		except Exception as exc:
#FileNotFoundError: [Errno 2] No such file or directory: '/bCNC/pendant/favicon.ico'
			print('mainPage:\n  Exception: %s'%(exc))

			self.wfile.write("""<!DOCTYPE html>
<html>
<head>
<title>Errortitle</title>
<meta name="viewport" content="width=device-width,initial-scale=1, user-scalable=yes" />
</head>
<body>
Page not found.
</body>
</html>
""".encode())


# -----------------------------------------------------------------------------
def _server(app):
	global httpd
	server_class = HTTPServer.HTTPServer
	try:
		httpd = server_class(('', port), Pendant)
		httpd.app = app
		httpd.serve_forever()
	except:
		httpd = None


# -----------------------------------------------------------------------------
def start(app):
	global httpd

	if httpd is not None: return False
	thread = threading.Thread(target=_server, args=(app,))
	thread.start()
	return True


# -----------------------------------------------------------------------------
def stop():
	global httpd
	if httpd is None: return False
	httpd.shutdown()
	httpd = None
	if Pendant.camera: Pendant.camera.stop()
	return True

if __name__ == '__main__':
	start()
```

**Comment by Guenni75** [comment]
Hi. After Updating to Ubuntu 20..., i made another try without the pendant.py above.
Browser and bCNC were on the same PC.
This is the Terminaltext:

Exception happened during processing of request from ('127.0.0.1', 46364)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------

Next i try the pendant.py above....

**Comment by Guenni75** [comment]
The same problem with the new pendant.py.

**Comment by Guenni75** [comment]
I installed the last bCNC with Python 2.7 on Win10 and the Pendant only shows a warning sign ;(

**Comment by Guenni75** [comment]
The same with the new pendant.py ;(

**Comment by GitHubCaps** [comment]
That is a common error that comes from socket (not bCNC) and can be ignored. But what about it actually working now with the patched file?

**Comment by Guenni75** [comment]
As I wrote above:

> The same with the new pendant.py ;(

**Comment by GitHubCaps** [comment]
Do you have any issues with serial communication between bCNC and your CNC machine? How are you connected from android to the pendant? Have you tried connecting bCNC using spy:// from the terminal to see what's going on? 

Lots of questions, but any info you can give would really be appreciated!

**Comment by GitHubCaps** [comment]
@Guenni75 At first, I did see that your video shows a part in it (it only flickered).
It seems to me that something is happening at network level connection wise.
Maybe, you can check out these #1072 and #1121
Possibly @qvisionsa or @PCSDIAS may have some info that can help you resolve this issue.

**Comment by Guenni75** [comment]
@GizHubCaps   Ar first, yes.... it flickers and you can see the part not even a second. That's why I opened this issue.

**Comment by Guenni75** [comment]
A have one bCnc on lubuntu and one on Win10. Both with Python 2.7.
The serial communication works without any issue.
At the Linux Version i have this flickering with and without a connection to the CNC (pendant opened on the same PC and on a remote PC).
At the Win10 Version the pendant shows no flickering, but a warning sign instead of the part.
On both Versions, moving, homing and so on works fine.
I don't know how to connect bCNC with Spy.

**Comment by GitHubCaps** [comment]
I noticed that the name of the file you were running is in unicode. Have you tested with an ascii formatted file and possibly using bCNC with English? May not be an issue, but wouldn't hurt to eliminate as much as possible.

As far as the `error` and `BrokenPipeError` py2/3 respectively, those can generally be ignored,(serial is negotiating connections) sometimes I have few show and other times non at all.

The flickering may be due to network connection issues (seeing that the part at least shows up) but not sure atm. Hopefully, if someone else has had this issue before, maybe we could get some more information.

In bCNC where you connect to usb `File -> Serial 
-> Port:` is where there is options for `spy:// `
Also there's info in the README and manual.

Note: I will have something up soon to fix some encoding bugs (for both) and the file open in py3
Don't know if that will help you or not, but we'll see.

**Comment by GitHubCaps** [comment]
@Guenni75 Also, if you can, zip the file and upload it here (drag/drop into comment box) so I can test it directly to see if it gives me the same issue.

**Comment by truglodite** [comment]
Just reporting in I am having the same issue. I'm running the latest dev on a pi3 using python3 (installed via pip yesterday). Both local browser and remote (chrome on win10) display the flickering issue. I have very little understanding to help troubleshoot any networking issues related to this, but I have seen in chrome Dev tools the same thing as pcsdias here:
https://github.com/vlachoudis/bCNC/issues/1121#issuecomment-452682544 

The canvas keeps failing to load, and I get the same error messages on the terminal of "An established connection was aborted by the software on the host computer". There is also a repeating message in chrome debug console `Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH`

I can share additional files/info if it would be helpful to fix this. I can say I have tried with several different gcode files and encoding does not appear to solve this. So I don't think it's anything to do with that. Also note I previously had installed bCNC with python2 a few months ago, and it was behaving the same way.

**Comment by Guenni75** [comment]
@GitHubCaps It doesn't matter which file i use. It's always the same.
Since a few months, i only get a warning sign.

**Comment by jsiddall** [comment]
I was having this problem with earlier builds but with the latest version it is working again, even with python3

**Comment by luckypickle1** [comment]
Make sure to install all dependecies including numpy for the latest version and you should have no problems
