### ISSUE TITLE
suddenly can't get bCNC running anymore

### ISSUE THREAD

**Issue by Nikoju** [vlachoudis/bCNC#1627]
Hi I've been using bCNC for quite some time and I loved working with it! 
However after trying to restart bCNC after a few months of not having the time to do any milling the window just opened but immediately froze before loading any of the controls.

I've tried reinstalling bCNC via pip and after this also didn't show any signs of success I uninstalled and reinstalled Python altogether but it still does not work...

I am using win10 and am getting the following response after executing "py -m bCNC":

```
new-config Utils <configparser.ConfigParser object at 0x000002904349FAC0>
================================================================================
WARNING: bCNC has been recently ported to support both python v2.x and v3.x
Most things seem to work reasonably well in both python versions.
Please report any issues to: https://github.com/vlachoudis/bCNC/issues
================================================================================
self.canvas.winfo_id(): 3345906
Using old style comports()!
Using old style comports()!
Using old style comports()!
Not Loading 6 axis displays
Not Loading 6 axis displays
```

I really hope someone can help me with this issue as I would really like to start milling again and I just have no clue what is going wrong here. Thanks!
Nikolaus

![grafik](https://user-images.githubusercontent.com/32682809/136707352-9f1e049f-f229-4466-a3db-bf86873b63b9.png)

**Comment by evilhope** [comment]
Hi, I have the same issue. did you resolved that issue?

**Comment by Nikoju** [comment]
Unfortunately I hav not yet been able to resolve the issue however I recently switched to a new PC on which it now runs flawlessly..

**Comment by Lylesgold** [comment]
A similar issue, Did a fresh install following a years long break from hobby CNC'ing. bCNC will not run on Windows 10 under  Python3. Issues the following when I input 'py -m bCNC ' or 'py -m bCNC --version':

Traceback (most recent call last):
  File "C:\Users\Normans\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Normans\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Normans\AppData\Local\Programs\Python\Python310\lib\site-packages\bCNC\__main__.py", line 50, in  
    <module> import Utils
  File "C:\Users\Normans\AppData\Local\Programs\Python\Python310\lib\site-packages\bCNC\Utils.py", line 41, in <module>
    if getattr( sys, 'frozen', False ):
NameError: name 'sys' is not defined

I spent a long time reinstalling... and looking at the code, it's beyond my ability. I suspect a totally clean install of Win10 would eradicate, but that would be too disruptive and I'm not prepared to do it yet, so can anyone please help?

**Comment by cshunt** [comment]
> A similar issue, Did a fresh install following a years long break from hobby CNC'ing. bCNC will not run on Windows 10 under Python3. Issues the following when I input 'py -m bCNC ' or 'py -m bCNC --version':
> 
> Traceback (most recent call last): File "C:\Users\Normans\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Users\Normans\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\Normans\AppData\Local\Programs\Python\Python310\lib\site-packages\bCNC__main__.py", line 50, in import Utils File "C:\Users\Normans\AppData\Local\Programs\Python\Python310\lib\site-packages\bCNC\Utils.py", line 41, in if getattr( sys, 'frozen', False ): NameError: name 'sys' is not defined
> 
> I spent a long time reinstalling... and looking at the code, it's beyond my ability. I suspect a totally clean install of Win10 would eradicate, but that would be too disruptive and I'm not prepared to do it yet, so can anyone please help?

It appears this issue has been resolved in the master branch. "Import sys" is missing from several files. It looks to be related to an update in python. utils.py, toolspage.py & filepage.py
