### ISSUE TITLE
Garbage receive MPos: <Idle|MPos:-46.835,83.830,-0.100FS:0,1000>

### ISSUE THREAD

**Issue by sugigpi** [vlachoudis/bCNC#1738]
i have a problem with bcnc, when bcnc is working it suddenly stops in the middle of the process, when i check it turns out there is a message in the terminal "garbage received" which asks how this can happen please ask for a solution friend, i use arduino uno and grbl shild thank you .

Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\Lib\site-packages\bCNC\Sender.py", line 786, in serialIO
    elif self.mcontrol.parseLine(line, cline, sline):
  File "C:\Python27\Lib\site-packages\bCNC\controllers\_GenericController.py", line 221, in parseLine
    self.parseBracketSquare(line)
  File "C:\Python27\Lib\site-packages\bCNC\controllers\GRBL1.py", line 206, in parseBracketSquare
    CNC.vars["prby"] = float(word[2])
ValueError: invalid literal for float(): 0.0000.000

![image](https://user-images.githubusercontent.com/70959123/184883742-5b2cb00f-57dc-44eb-b737-c4affeb76805.png)

**Comment by rschell** [comment]
> File "C:\Python27\Lib\site-packages\bCNC\controllers\GRBL1.py", line 206, in parseBracketSquare
> CNC.vars["prby"] = float(word[2])
> ValueError: invalid literal for float(): 0.0000.000

Traceback suggests a formatting issue in the gcode file.

**Comment by sugigpi** [comment]
After I installed a new version of python, the problem is still the same, sometimes the error still comes out, but I switch to another usb port sometimes the problem can be solved, but it's really annoying when I'm working. thanks for the advice bro.

**Comment by sugigpi** [comment]
> > File "C:\Python27\Lib\site-packages\bCNC\controllers\GRBL1.py", line 206, in parseBracketSquare
> > CNC.vars["prby"] = float(word[2])
> > ValueError: invalid literal for float(): 0.0000.000
> 
> Traceback suggests a formatting issue in the gcode file.

thanks bro i will try

**Comment by sugigpi** [comment]
> > File "C:\Python27\Lib\site-packages\bCNC\controllers\GRBL1.py", line 206, in parseBracketSquare
> > CNC.vars["prby"] = float(word[2])
> > ValueError: invalid literal for float(): 0.0000.000
> 
> Traceback suggests a formatting issue in the gcode file.


After I installed a new version of python, the problem is still the same, sometimes the error still comes out, but I switch to another usb port sometimes the problem can be solved, but it's really annoying when I'm working. thanks for the advice bro.

**Comment by sugigpi** [comment]
> > File "C:\Python27\Lib\site-packages\bCNC\controllers\GRBL1.py", line 206, in parseBracketSquare
> > CNC.vars["prby"] = float(word[2])
> > ValueError: invalid literal for float(): 0.0000.000
> 
> Traceback suggests a formatting issue in the gcode file.
