### ISSUE TITLE
100% reproducible: Crash after "scan"

### ISSUE THREAD

**Issue by stefan-eh** [vlachoudis/bCNC#1892]
Hi,
 
I am using bCNC latest from github with a "Genmitsu 3018-ProVer V2" and Python 3.11 on a "Debian testing"-PC. 

Unfortunately, I could not get any useful results, since bCNC crashes in several situations. Good thing: the crashes are 100% reproducible and this is the fastest way to do it:

- connect
- load nc file
- do a homing cycle
- click "Probe" -> "Autolevel" -> "Scan"

The crash happens after the scan seems to be complete. Every time, console output looks like this:
 
> Exception in thread Thread-2 (serialIO):
> Traceback (most recent call last):
>   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.11/threading.py", line 982, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/dean/syncthing/pc/electronics/bcnc/venv/lib/python3.11/site-packages/bCNC/Sender.py", line 835, in serialIO
>     elif self.mcontrol.parseLine(line, cline, sline):
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/dean/syncthing/pc/electronics/bcnc/venv/lib/python3.11/site-packages/bCNC/controllers/_GenericController.py", line 298, in parseLine
>     "GRBL%d" % (int(CNC.vars["version"][0])))
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> ValueError: invalid literal for int() with base 10: 'f'
 
Can you please help in resolving this?     

regards
Stefan

**Comment by doosedev** [comment]
I can reproduce this as well, using a Genmitsu 3020-Pro Max V2. Some preliminary digging and I found the text "Grbl for ARM32" being sent by the controller, and misinterpreted by the GenericController as a version number (which causes it to fail). Potential fix might be discarding any line that reaches such point but doesn't have a numeric character in char 0?
