### ISSUE TITLE
Tile Error

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#196]
I was attempting to create a plugin, that would do something similar to Tile. Although Tile does not seem to work for me. I'm working on master branch 'Removed "running" condition from probe' `8c9b74b968a3335e7c45887d5633c21bf91608f1`

     Connected to pydev debugger (build 141.1116)
     Traceback (most recent call last):
       File "C:/Users/PycharmProjects/bCNC\Utils.py", line 303, in __call__
         return self.func(*args)
       File "C:/Users/frankwiebenga/PycharmProjects/bCNC\ToolsPage.py", line 1197, in execute
         self.tools.getActive().execute(self.app)
       File "C:\Users\frankwiebenga\PycharmProjects\bCNC\plugins\tile.py", line 87, in execute
         app.gcode.moveLines(newblocks, x, y)
       File "C:/Users/frankwiebenga/PycharmProjects/bCNC\CNC.py", line 3169, in moveLines
         return self.process(items, self.moveFunc, Tab.move, dx, dy, dz)
       File "C:/Users/frankwiebenga/PycharmProjects/bCNC\CNC.py", line 3106, in process
         for bid,lid in self.iterate(items):
       File "C:/Users/frankwiebenga/PycharmProjects/bCNC\CNC.py", line 2674, in iterate
         for i in block.tabs:
     AttributeError: 'Block' object has no attribute 'tabs'

**Comment by vlachoudis** [comment]
I forgot to copy the tabs attribute in the copy constructor of the Block. Now it is ok.
