### ISSUE TITLE
Problem don't start

### ISSUE THREAD

**Issue by el3kim** [vlachoudis/bCNC#372]
elk@elk-hp:~/bCNC-master$ ./bCNC

Traceback (most recent call last):
  File "./bCNC.py", line 2443, in <module>
    application = Application(tk)
  File "./bCNC.py", line 193, in __init__
    page = cls(self.ribbon, self)
  File "/home/elk/bCNC-master/CNCRibbon.py", line 106, in __init__
    self.register()
  File "/home/elk/bCNC-master/ControlPage.py", line 1102, in register
    (DROFrame, ControlFrame, StateFrame))
  File "/home/elk/bCNC-master/CNCRibbon.py", line 125, in _register
    w = f(self.master._pageFrame, self.app)
  File "/home/elk/bCNC-master/ControlPage.py", line 142, in __init__
    DROFrame.dro_mpos   = Utils.getFont("dro.mpos",   DROFrame.dro_mpos)
  File "/home/elk/bCNC-master/Utils.py", line 260, in getFont
    font = makeFont(name, value)
  File "/home/elk/bCNC-master/Utils.py", line 212, in makeFont
    font.configure(family=value[0], size=value[1])
IndexError: tuple index out of range

**Comment by Effer** [comment]
Hi @el3kim ,

can you post here your **.bCNC** User File? You can reach it from here:
![image](https://cloud.githubusercontent.com/assets/1007007/16682344/6211903e-44fa-11e6-9df7-9ad854b082ad.png)

Or in your user folder as described here: https://github.com/vlachoudis/bCNC/wiki/Configuration

I suppose some font settings is wrong. If so we'll add some security check.

**Comment by vlachoudis** [comment]
@el3kim It seems that the size was not supplied in one font and I didn't have a protection on that. I've just added one, so now you should be able to start and correct the problematic font

**Comment by el3kim** [comment]
Thanks you.
Great work.
