### ISSUE TITLE
bCNC freezing and unable to close.

### ISSUE THREAD

**Issue by mano1979** [vlachoudis/bCNC#780]
Sometimes bCNC freezes up and i am unable to close it.  First i try the red "close" button in bCNC but that never works. Then i got to the terminal that i used to start bCNC, and press CTRL+C. This kinda works but it never goes back to the command line. After pressing CTRL+Z it is shutdown in the terminal, and no active instance of bCNC can be found. But the bCNC window stays open and i am unable to close it. i have to reboot my pc to get rid of it.

I recently picked up on cnc-ing again, and updated bCNC. But with the older version i used before, i never had this problem.

**Comment by vlachoudis** [comment]
Hi @mano1979 could you provide more information which version of bCNC was working, what OS, do you see any messages in the terminal etc.

**Comment by mano1979** [comment]
I am on linux (ubuntu 14.04). The previous version i used is unknown. But it was at least 2 years old. O checked for messages in the terminal. Initially i get no messages but on a bad crash, when i stop it with CTRL+Z it throws this: (see next message)

**Comment by mano1979** [comment]
`Traceback (most recent call last):
  File "./bCNC.py", line 2530, in <module>
    application = Application(tk)
  File "./bCNC.py", line 459, in __init__
    self.openClose()
  File "./bCNC.py", line 2051, in openClose
    if self.open(device, baudrate):
  File "./bCNC.py", line 2066, in open
    parent=self)
  File "/usr/lib/python2.7/lib-tk/tkMessageBox.py", line 91, in showerror
    return _show(title, message, ERROR, OK, **options)
  File "/usr/lib/python2.7/lib-tk/tkMessageBox.py", line 72, in _show
    res = Message(**options).show()
  File "/usr/lib/python2.7/lib-tk/tkCommonDialog.py", line 48, in show
    s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError: can't invoke "grab" command: application has been destroyed
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545258c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447e6c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454e6c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447a8c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545226c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d0cc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447b4c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d48c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54541ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452f0c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454aec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544dd6c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d18c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452bac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545240c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d8ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452b0c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544792c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545476c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545410c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54527ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d9cc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d1ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544dc6c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545464c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54522cc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54540ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d3cc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447d0c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447cac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545486c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d5ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545408c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452c6c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544de2c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545270c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447f2c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54523ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545482c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544776c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54526ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452e4c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54571ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54479ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454c8c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544794c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452ccc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454a2c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54529cc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454dec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454e0c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452f2c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545424c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545212c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545252c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454eec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454c2c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447c4c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545456c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544dacc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454f6c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545448c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452d8c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545436c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454d0c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452c0c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54570ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454fcc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454b2c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545478c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545494c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54525ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447aac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545246c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454cec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545710c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545296c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544782c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545492c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545206c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d2ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544db8c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454d8c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545722c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54549ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447f6c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452eac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447fcc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545266c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d9ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54477ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d12c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544df2c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54542cc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452fac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545442c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544dc4c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545470c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545708c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d96c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545402c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54527ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447bec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54478ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544decc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447dcc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54528ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544dccc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452a2c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545428c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54524cc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d90c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544ddcc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545208c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545726c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54521ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544de6c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452d2c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545284c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545218c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d32c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d54c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545720c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d06c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544dfec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447d8c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54545ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544daec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545422c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54544ac>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447e8c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454ecc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454a0c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452dec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545488c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447d2c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d4ec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d66c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d74c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544dbec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447f0c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544784c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545220c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545234c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454fec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544da6c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb545466c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454b8c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb54543cc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d60c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544df8c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d24c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5454acc>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452a8c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5452aec>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb544d30c>> ignored
Exception _tkinter.TclError: TclError('can\'t invoke "image" command: application has been destroyed',) in <bound method PhotoImage.__del__ of <Tkinter.PhotoImage instance at 0xb5447aec>> ignored
`

**Comment by jpascher** [comment]
I have the same problem i am using windows 10 and python 2.7.4 with serial driver 3.4  different errors will be displayed like "hard limit" but one cant get  on. It is summular ti the behaviear as i have if use the setup window and push the final button. I did do the settings via editing the ini file and i don touch the Window for graphical setup. Would be quite happy with it if this Problem would not cores a complete new start and kill of the old instance.

**Comment by jpascher** [comment]
Hi i had an intense look into it and the problem is in connection with the communication of the grbl1.1.
I ha a look at the terminal window the fist time one saves a config to the grbl CNC it sends the code but i stops with 25%. To get back one can use the stop send butten. On could sen commandline $$ before but not after. repeating this results also in not sending commands.

**Comment by Harvie** [comment]
is this still issue with latest master?
