### ISSUE TITLE
cannot profile a circle

### ISSUE THREAD

**Issue by biffhero** [vlachoudis/bCNC#842]
Have a .dxf file which is only one circle.  when I click on Profile, I get the following traceback:

Traceback (most recent call last):
  File "/home/rob/src/bCNC/Utils.py", line 417, in __call__
    return self.func(*args)
  File "/home/rob/src/bCNC/ToolsPage.py", line 1490, in execute
    self.tools.getActive().execute(self.app)
  File "/home/rob/src/bCNC/ToolsPage.py", line 748, in execute
    app.profile(direction, self["offset"], self["overcut"], name)
  File "./bCNC.py", line 1736, in profile
    msg = self.gcode.profile(blocks, ofs*sign, overcut, name)
  File "/home/rob/src/bCNC/CNC.py", line 3522, in profile
    opath.removeExcluded(path, D*offset)
  File "/home/rob/src/bCNC/lib/bpath.py", line 951, in removeExcluded
    include, last = isClose(self[0].midPoint(), last)
  File "/home/rob/src/bCNC/lib/bpath.py", line 940, in isClose
    if path[i].distance(P) < chkofs:
IndexError: list index out of range

**Comment by biffhero** [comment]
I figure I just did something wrong in the workflow, as I can't imagine anything this simple being a problem.

**Comment by vlachoudis** [comment]
@biffhero apparently it was a bug that was introduced recently to speed up the profiling of complex regions, and it completely missed the very simple ones :)
Now it should be fixed. Please download again.
