### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 2: ordinal not in range(128)

### ISSUE THREAD

**Issue by Harvie** [vlachoudis/bCNC#940]
After last archlinux upgrade, the open dialog refuse to open file. I can only open recent files, but not select files using file dialog. It affects both latest git and stable bCNC version 0.9.11. It gives me this:

```
Traceback (most recent call last):
  File "/home/harvie/Temp/bCNC/Utils.py", line 434, in __call__
    return self.func(*args)
  File "bCNC.py", line 1947, in loadDialog
    filetypes=FILETYPES)
  File "/home/harvie/Temp/bCNC/lib/bFileDialog.py", line 925, in askopenfilename
    return OpenDialog(**options).show()
  File "/home/harvie/Temp/bCNC/lib/bFileDialog.py", line 366, in show
    self.typeCombo.set(self.typeCombo.get(0))	# will fill the files
  File "/home/harvie/Temp/bCNC/lib/tkExtra.py", line 3058, in set
    self.invoke()
  File "/home/harvie/Temp/bCNC/lib/tkExtra.py", line 3010, in invoke
    self.command()
  File "/home/harvie/Temp/bCNC/lib/bFileDialog.py", line 765, in typeChange
    self.fill()
  File "/home/harvie/Temp/bCNC/lib/bFileDialog.py", line 552, in fill
    filename = os.path.join(path, fn)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 2: ordinal not in range(128)
```
Have you ever experienced this?

**Comment by Harvie** [comment]
Workaround:
This only happens for directories, which contain filenames with funky characters. Unfortunately bCNC remembers last directory used and once you get into that directory, you will always trigger the bug when hitting open button. To get this going again, i had to edit following line in ~/.bCNC to point to some directory without such files:

```
[File]
dir = /home/harvie/Work
...
```

**Comment by Harvie** [comment]
This cannot be fixed until Python3
